[pytest]
testpaths =
    tests
python_files =
    test_*.py
asyncio_mode = strict
addopts =
    --cov=application
    --cov=core
    --cov=di
    --cov=infrastructure
    --cov=presentation
    --cov-branch
    --cov-report=term-missing:skip-covered
    --cov-report=html:htmlcov
